### ISSUE TITLE
Edge (on Win10): filters in navigation panel disappear

### ISSUE THREAD

**Issue by pascalmfrey** [infect-org/frontend#109] opened 2017-11-24 17:26 UTC
This is a similar error in what appeared in [IE 11](https://github.com/infect-org/frontend/issues/96?_pjax=%23js-repo-pjax-container), here in Edge browser on Win10 (tell me if you need exact version numbers).
When a filter is chosen either through click action or through the search bar, all filters in the filter navigation panel diappear. 
JS is "main.56dbe99bca3947fa7e4c.js"
Error messages see attached pics below:

![edge disappearing menu bug](https://user-images.githubusercontent.com/1735457/33219743-63a4586e-d144-11e7-8853-b3889a22ca3f.PNG)

**Comment by fxstr** [comment] 2017-11-29 08:03
@pascalmfrey That's like reeeeallyreaallyreally strange. I've looked through the whole deployed code, there is no `scrollTo` method call anywhere – anymore: It was removed a few weeks ago. Is there any chance you're still being delivered an old version of the application? Any chance you could do a hard refresh (`CTRL + F5`)?

**Comment by pascalmfrey** [comment] 2017-12-02 04:48
I've double checkt, the error is still there, even after hard refresh (and on a new pc where infect has never been opened before).

As a hint that might help: the call to "scrollTo" is found within the file mostUsedFilterList.jsx within the components "filterList" on line 80:

![filterlist](https://user-images.githubusercontent.com/1735457/33511868-5f6b1914-d724-11e7-977a-e18b6f480516.png)

**Comment by fxstr** [comment] 2017-12-02 12:32
@pascalmfrey Thanks a lot, mate – I had overseen that use of scrollTop 🤦‍♂️ . The issue is fixed now, release pending.

**Closed by fxstr** 2017-12-02 12:32 UTC
